# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'munch-madness' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for munch-madness
  pod 'Firebase'
  pod 'Firebase/Database'
  pod 'Firebase/InAppMessaging'
  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Auth'
end
